export const textStyles = {
  'h1-primary': {
    fontSize: { base: '2.5rem', md: '4.5rem' },
    lineHeight: { base: '3rem', md: '5rem' },
    fontWeight: 400,
    fontFamily: 'Anton',
    color: 'neutral.10',
    textTransform: 'uppercase',
  },
  'h1-secondary': {
    fontSize: { base: '2.5rem', md: '4.5rem' },
    lineHeight: { base: '3rem', md: '5rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'h2-primary': {
    fontSize: { base: '2.5rem', md: '3.5rem' },
    lineHeight: { base: '3rem', md: '4rem' },
    fontWeight: 400,
    fontFamily: 'Anton',
    color: 'neutral.10',
    textTransform: 'uppercase',
  },
  'h2-secondary': {
    fontSize: { base: '2.5rem', md: '3.5rem' },
    lineHeight: { base: '3rem', md: '4rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'h3-primary': {
    fontSize: { base: '2rem', md: '3rem' },
    lineHeight: { base: '2.5rem', md: '3.5rem' },
    fontWeight: 400,
    fontFamily: 'Anton',
    color: 'neutral.10',
  },
  'h3-secondary': {
    fontSize: { base: '2rem', md: '3rem' },
    lineHeight: { base: '2.5rem', md: '3.5rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'h4-primary': {
    fontSize: { base: '1.5rem', md: '2.5rem' },
    lineHeight: { base: '2rem', md: '3rem' },
    fontWeight: 400,
    fontFamily: 'Anton',
    color: 'neutral.10',
  },
  'h4-secondary': {
    fontSize: { base: '1.5rem', md: '2.5rem' },
    lineHeight: { base: '2rem', md: '3rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'h5-primary': {
    fontSize: { base: '1.5rem', md: '2rem' },
    lineHeight: { base: '2rem', md: '2.5rem' },
    fontWeight: 400,
    fontFamily: 'Anton',
    color: 'neutral.10',
    textTransform: 'uppercase',
  },
  'h5-secondary': {
    fontSize: { base: '1.5rem', md: '2rem' },
    lineHeight: { base: '2rem', md: '2.5rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'h6-primary': {
    fontSize: { base: '1.5rem', md: '1.5rem' },
    lineHeight: { base: '2rem', md: '2rem' },
    fontWeight: 400,
    fontFamily: 'Anton',
    color: 'neutral.10',
  },
  'h6-secondary': {
    fontSize: { base: '1.5rem', md: '1.5rem' },
    lineHeight: { base: '2rem', md: '2rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'h7-primary': {
    fontSize: { base: '1.25rem' },
    lineHeight: { base: '1.75rem' },
    fontWeight: 400,
    fontFamily: 'Anton',
    color: 'neutral.10',
  },
  'h7-secondary': {
    fontSize: { base: '1.25rem' },
    lineHeight: { base: '1.75rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'body-18-bold': {
    fontSize: { base: '1.125rem' },
    lineHeight: { base: '1.625rem' },
    fontWeight: 700,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'body-18': {
    fontSize: { base: '1.125rem' },
    lineHeight: { base: '1.625rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'body-18-italic': {
    fontSize: { base: '1.125rem' },
    lineHeight: { base: '1.625rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    fontStyle: 'italic',
    color: 'neutral.10',
  },
  'body-18-strikethrough': {
    fontSize: { base: '1.125rem' },
    lineHeight: { base: '1.625rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    textDecoration: 'line-through',
    color: 'neutral.10',
  },
  'body-16-bold': {
    fontSize: { base: '1rem' },
    lineHeight: { base: '1.5rem' },
    fontWeight: 700,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'body-16': {
    fontSize: { base: '1rem' },
    lineHeight: { base: '1.5rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'body-16-italic': {
    fontSize: { base: '1rem' },
    lineHeight: { base: '1.5rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    fontStyle: 'italic',
    color: 'neutral.10',
  },
  'body-16-strikethrough': {
    fontSize: { base: '1rem' },
    lineHeight: { base: '1.5rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    textDecoration: 'line-through',
    color: 'neutral.10',
  },
  'body-14-bold': {
    fontSize: { base: '0.875rem' },
    lineHeight: { base: '1.375rem' },
    fontWeight: 700,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'body-14': {
    fontSize: { base: '0.875rem' },
    lineHeight: { base: '1.375rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'body-14-italic': {
    fontSize: { base: '0.875rem' },
    lineHeight: { base: '1.375rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    fontStyle: 'italic',
    color: 'neutral.10',
  },
  'body-14-strikethrough': {
    fontSize: { base: '0.875rem' },
    lineHeight: { base: '1.375rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    textDecoration: 'line-through',
    color: 'neutral.10',
  },
  'caption-12-bold': {
    fontSize: { base: '0.75rem' },
    lineHeight: { base: '1.125rem' },
    fontWeight: 700,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'caption-12': {
    fontSize: { base: '0.75rem' },
    lineHeight: { base: '1.125rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'caption-12-uppercase': {
    fontSize: { base: '0.75rem' },
    lineHeight: { base: '1.125rem' },
    fontWeight: 700,
    fontFamily: 'Titillium',
    textTransform: 'uppercase',
    color: 'neutral.10',
  },
  'caption-12-strikethrough': {
    fontSize: { base: '0.75rem' },
    lineHeight: { base: '1.125rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    textDecoration: 'line-through',
    color: 'neutral.10',
  },
  'caption-10-bold': {
    fontSize: { base: '0.625rem' },
    lineHeight: { base: '1rem' },
    fontWeight: 700,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'caption-10': {
    fontSize: { base: '0.625rem' },
    lineHeight: { base: '1rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    color: 'neutral.10',
  },
  'caption-10-uppercase': {
    fontSize: { base: '0.625rem' },
    lineHeight: { base: '1rem' },
    fontWeight: 700,
    fontFamily: 'Titillium',
    textTransform: 'uppercase',
    color: 'neutral.10',
  },
  'caption-10-strikethrough': {
    fontSize: { base: '0.625rem' },
    lineHeight: { base: '1rem' },
    fontWeight: 400,
    fontFamily: 'Titillium',
    textDecoration: 'line-through',
    color: 'neutral.10',
  },
};
